from datetime import datetime, timedelta

DEMO_ASSETS = [
    {"source":"google-drive","source_account":"acme.example","external_id":"gdrive://finance/q4-board-forecast.xlsx","name":"Q4 Board Forecast.xlsx","path":"Finance/Board/Q4 Board Forecast.xlsx","mime_type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","size_bytes":284112,"owner":"mia.chen@acme.example","created_at":datetime.utcnow()-timedelta(days=520),"modified_at":datetime.utcnow()-timedelta(days=22),"last_accessed_at":datetime.utcnow()-timedelta(days=4),"encryption":"Provider managed","public_access":False},
    {"source":"aws-s3","source_account":"prod-customer-exports","external_id":"s3://prod-customer-exports/archive/customer_export_2023.csv","name":"customer_export_2023.csv","path":"s3://prod-customer-exports/archive/customer_export_2023.csv","mime_type":"text/csv","size_bytes":18642109,"owner":"data-platform@acme.example","created_at":datetime.utcnow()-timedelta(days=1110),"modified_at":datetime.utcnow()-timedelta(days=820),"last_accessed_at":datetime.utcnow()-timedelta(days=808),"encryption":"AES256","public_access":False},
    {"source":"microsoft-365","source_account":"acme.onmicrosoft.com","external_id":"sharepoint://legal/vendor-nda-final.docx","name":"Vendor NDA - Final.docx","path":"Legal/Contracts/Vendor NDA - Final.docx","mime_type":"application/vnd.openxmlformats-officedocument.wordprocessingml.document","size_bytes":92144,"owner":"legal@acme.example","created_at":datetime.utcnow()-timedelta(days=890),"modified_at":datetime.utcnow()-timedelta(days=621),"last_accessed_at":datetime.utcnow()-timedelta(days=410),"encryption":"Provider managed","public_access":False},
    {"source":"github","source_account":"acme-platform","external_id":"github://acme-platform/payments-api/config/production.env","name":"production.env","path":"payments-api/config/production.env","mime_type":"text/plain","size_bytes":3941,"owner":"platform-security@acme.example","created_at":datetime.utcnow()-timedelta(days=190),"modified_at":datetime.utcnow()-timedelta(days=2),"last_accessed_at":datetime.utcnow()-timedelta(days=1),"encryption":"Repository encryption","public_access":False},
    {"source":"postgres","source_account":"analytics-prod","external_id":"postgres://analytics-prod/public.patient_claims","name":"patient_claims","path":"analytics-prod.public.patient_claims","mime_type":"application/x-database-table","size_bytes":774421222,"owner":"analytics@acme.example","created_at":datetime.utcnow()-timedelta(days=760),"modified_at":datetime.utcnow()-timedelta(days=0),"last_accessed_at":datetime.utcnow()-timedelta(days=0),"encryption":"KMS","public_access":False},
    {"source":"google-drive","source_account":"acme.example","external_id":"gdrive://marketing/public-product-faq.pdf","name":"Public Product FAQ.pdf","path":"Marketing/Public/Public Product FAQ.pdf","mime_type":"application/pdf","size_bytes":610422,"owner":"marketing@acme.example","created_at":datetime.utcnow()-timedelta(days=44),"modified_at":datetime.utcnow()-timedelta(days=12),"last_accessed_at":datetime.utcnow()-timedelta(days=1),"encryption":"Provider managed","public_access":True},
    {"source":"aws-s3","source_account":"security-logs","external_id":"s3://security-logs/incidents/incident-2024-017.json","name":"incident-2024-017.json","path":"s3://security-logs/incidents/incident-2024-017.json","mime_type":"application/json","size_bytes":182733,"owner":"security@acme.example","created_at":datetime.utcnow()-timedelta(days=620),"modified_at":datetime.utcnow()-timedelta(days=610),"last_accessed_at":datetime.utcnow()-timedelta(days=205),"encryption":"aws:kms","public_access":False},
    {"source":"microsoft-365","source_account":"acme.onmicrosoft.com","external_id":"onedrive://hr/employee-payroll-2022.xlsx","name":"Employee Payroll 2022.xlsx","path":"HR/Payroll/Employee Payroll 2022.xlsx","mime_type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","size_bytes":1244221,"owner":"hr-ops@acme.example","created_at":datetime.utcnow()-timedelta(days=1310),"modified_at":datetime.utcnow()-timedelta(days=1120),"last_accessed_at":datetime.utcnow()-timedelta(days=1010),"encryption":"Provider managed","public_access":False},
    {"source":"github","source_account":"acme-platform","external_id":"github://acme-platform/iac/main.tf","name":"main.tf","path":"infrastructure/aws/main.tf","mime_type":"text/plain","size_bytes":48820,"owner":"cloud-engineering@acme.example","created_at":datetime.utcnow()-timedelta(days=460),"modified_at":datetime.utcnow()-timedelta(days=7),"last_accessed_at":datetime.utcnow()-timedelta(days=2),"encryption":"Repository encryption","public_access":False},
    {"source":"aws-s3","source_account":"website-assets","external_id":"s3://website-assets/brand/logo.svg","name":"logo.svg","path":"s3://website-assets/brand/logo.svg","mime_type":"image/svg+xml","size_bytes":12088,"owner":"web@acme.example","created_at":datetime.utcnow()-timedelta(days=220),"modified_at":datetime.utcnow()-timedelta(days=18),"last_accessed_at":datetime.utcnow()-timedelta(days=0),"encryption":"AES256","public_access":True},
]
